Use string concatenation for header building
nodejs/llparse pull request #59
Opened 2024-04-08 23:13 UTC by RedYetiDev

This PR uses string concatenation to build the header, rather than repeated redefinitions with `+=`

2024-04-08 23:16 UTC, WellHiIGuess commented
Can't believe no one thought to change this before

2024-04-08 23:18 UTC, RedYetiDev commented
> Can't believe no one thought to change this before

Well, for readability reasons, it may have been preferable in the past, but every time `+=` is used, it is a redundant re-assignment of a variable, so by using `'...' + '...'`, I am lowering the re-assignment count.

Technically, template literals could also be used, but for readability reasons, I chose against them

2024-08-03 08:37 UTC, Uzlopak requested changes
There is no need for the intermediary defineGuard variable

2024-08-03 08:37 UTC, Uzlopak commented on src/compiler/header-builder.ts
> +    return defineGuard +
```suggestion
    return '#ifndef ${DEFINE}\n#define ${DEFINE}\n' +
```

2024-08-03 08:37 UTC, Uzlopak commented on src/compiler/header-builder.ts
> +    const defineGuard = `#ifndef ${DEFINE}\n#define ${DEFINE}\n`;
```suggestion
```

2025-04-24 17:40 UTC, closed without merging